[tool.poetry]
name = "paystack-cli"
version = "0.1.0"
description = ""
authors = ["Gbenga Adeyi <adeyigbenga005@gmail.com>"]
readme = "README.md"
packages = [{include = "paystack_cli"}]

[tool.poetry.dependencies]
python = "^3.9"
pypaystack2 = "^2.0.0"
typer = {extras = ["all"], version = "^0.9.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
